Update msys2-bootstrap.yml

diff --git a/ci/msys2-bootstrap.yml b/ci/msys2-bootstrap.yml
--- a/ci/msys2-bootstrap.yml
+++ b/ci/msys2-bootstrap.yml
@@ -29,23 +29,13 @@
 
 variables:
   CHERE_INVOKING: enabled_from_arguments
-  MSYSCON: defterm
   MSYS2_INSTALL_DIR: 'C:\msys64'
-  PACMAN_ARCHIVE: '/var/cache/pacman/pkg'
-
+  MSYSCON: defterm
+  MSYSTEM: MSYS
+  # PACMAN_ARCHIVE: '/var/cache/pacman/pkg'
+  PACMAN_ARCHIVE: '$(Pipeline.Workspace)/pacman-archive'
 pool:
   vmImage: 'windows-2019'
-
-strategy:
-  matrix:
-    MINGW32:
-      MINGW: mingw32
-      MSYSTEM: MINGW32
-      MSYSTEM_CARCH: i686
-    MINGW64:
-      MINGW: mingw64
-      MSYSTEM: MINGW64
-      MSYSTEM_CARCH: x86_64
 
 steps:
 - bash: |
@@ -53,18 +43,20 @@ steps:
     echo \$SHELL
     ls -l \$SHELL
     for I in bash git cmake ninja gcc g++ clang clang++; do
-      echo "\$I:" `which \$I` || true
+      echo -n "\$I:"
+      which \$I || true
     done
-    echo "/mingw64/bin:" `cygpath -w /mingw64/bin`
+    echo -n "/mingw64/bin:"
+    cygpath -w /mingw64/bin
     env | sort
     END_CI
   displayName: Analyse environment
 
 - bash: |
-    export MSYSTEM=MSYS2
     ci/msys2bash.cmd -s << END_CI
-    echo "$(PACMAN_ARCHIVE):" `ls '$(PACMAN_ARCHIVE)'`
-    pacman --noconfirm -Sy --needed \
+    echo -n "$(PACMAN_ARCHIVE):"
+    ls '$(PACMAN_ARCHIVE)'
+    pacman --cachedir '$(PACMAN_ARCHIVE)' --noconfirm -Sy --needed \
       bison \
       diffutils \
       flex \
@@ -75,57 +67,55 @@ steps:
       patch \
       python \
       sharutils \
-      mingw-w64-\${MSYSTEM_CARCH}-binutils \
-      mingw-w64-\${MSYSTEM_CARCH}-cmake \
-      mingw-w64-\${MSYSTEM_CARCH}-gcc \
-      mingw-w64-\${MSYSTEM_CARCH}-headers-git \
-      mingw-w64-\${MSYSTEM_CARCH}-nsis \
-      mingw-w64-\${MSYSTEM_CARCH}-tools-git  \
-      mingw-w64-\${MSYSTEM_CARCH}-winpthreads-git \
+      mingw-w64-{x86_64,i686}-binutils \
+      mingw-w64-{x86_64,i686}-cmake \
+      mingw-w64-{x86_64,i686}-gcc \
+      mingw-w64-{x86_64,i686}-headers-git \
+      mingw-w64-{x86_64,i686}-nsis \
+      mingw-w64-{x86_64,i686}-tools-git  \
+      mingw-w64-{x86_64,i686}-winpthreads-git \
       2>error.log || cat error.log
     echo "$(PACMAN_ARCHIVE):" `ls $(PACMAN_ARCHIVE)`
     END_CI
-  condition: not(variables['openorienteering.superbuild.msysBuildId'])
   displayName: 'Install MSYS2 MinGW packages for OpenOrienteering Superbuild'
   
 - bash: |
-    export MSYSTEM=MSYS2
     ci/msys2bash.cmd -s << END_CI
-    pacman --noconfirm -Scc
+    pacman --cachedir '$(PACMAN_ARCHIVE)' --noconfirm -Scc
     echo "$(PACMAN_ARCHIVE):" `ls $(PACMAN_ARCHIVE)`
     END_CI
-  #condition: not(variables['openorienteering.superbuild.msysBuildId'])
   displayName: 'Reduce installation size for CI'
 
 - bash: |
-    export MSYSTEM=MSYS2
     ci/msys2bash.cmd -s << END_CI
-    cd /${MINGW}
-    mkdir -p superbuild/share/doc/copyright
-    cat share/licenses/gcc-libs/README          >  superbuild/share/doc/copyright/gcc-libs-msys2.txt
-    echo ===                                    >> superbuild/share/doc/copyright/gcc-libs-msys2.txt
-    cat share/licenses/gcc-libs/COPYING.RUNTIME >> superbuild/share/doc/copyright/gcc-libs-msys2.txt
-    # Deprecation warning: Mapper still looks for gnustl*. It should use gcc-libs* instead.
-    cat superbuild/share/doc/copyright/gcc-libs-msys2.txt > superbuild/share/doc/copyright/gnustl-msys2.txt
-    
-    cat share/licenses/libwinpthread/mingw-w64-libraries/winpthreads/COPYING > superbuild/share/doc/copyright/winpthreads-msys2.txt
-    
-    cat share/licenses/libwinpthread/COPYING > superbuild/share/doc/copyright/mingw-w64-msys2.txt
+    for MINGW in mingw32 mingw64; do
+        cd /\${MINGW}
+        mkdir -p superbuild/share/doc/copyright
+        cat share/licenses/gcc-libs/README          >  superbuild/share/doc/copyright/gcc-libs-msys2.txt
+        echo ===                                    >> superbuild/share/doc/copyright/gcc-libs-msys2.txt
+        cat share/licenses/gcc-libs/COPYING.RUNTIME >> superbuild/share/doc/copyright/gcc-libs-msys2.txt
+        # Deprecation warning: Mapper still looks for gnustl*. It should use gcc-libs* instead.
+        cat superbuild/share/doc/copyright/gcc-libs-msys2.txt > superbuild/share/doc/copyright/gnustl-msys2.txt
+        
+        cat share/licenses/libwinpthread/mingw-w64-libraries/winpthreads/COPYING > superbuild/share/doc/copyright/winpthreads-msys2.txt
+        
+        cat share/licenses/libwinpthread/COPYING > superbuild/share/doc/copyright/mingw-w64-msys2.txt
+    done
     END_CI
   displayName: 'Generate copyright files for toolchain libraries'
 
-- publish: $(MSYS2_INSTALL_DIR)
-  artifact: MSYS2-$(MINGW)-base
-  displayName: 'Publish MSYS2 base artifacts'
-  condition: false
+- publish: $(PACMAN_ARCHIVE)
+  artifact: MSYS2-pacman-archiv
+  displayName: 'Publish MSYS2 pacman archive'
 
 - bash: |
-    export MSYSTEM=MSYS2
     ci/msys2bash.cmd -s << END_CI
     mkdir -p mingw-source
     cd mingw-source
     
     export LANG=C
+    MINGW=mingw64
+    MSYSTEM_CARCH=x86_64
     pacman -Qo /\${MINGW}/bin/libstdc++-6.dll \
       | sed "s,-gcc-libs,-gcc," \
       | sed "s,\.*owned by mingw-w64-\${MSYSTEM_CARCH},https://repo.msys2.org/mingw/sources/mingw-w64,;s, ,-,;s, *$,.src.tar.gz," > urls.txt
@@ -139,11 +129,10 @@ steps:
     
     cat urls.txt
     wget --no-verbose -i urls.txt 2>&1 \
-      || echo "##vso[task.LogIssue type=warning]Failed to download some $(MINGW) source tarballs."
+      || echo "##vso[task.LogIssue type=warning]Failed to download some \${MINGW} source tarballs."
     END_CI
   displayName: 'Get extra source tarballs'
 
 - publish: $(Build.SourcesDirectory)\mingw-source
-  artifact: MSYS2-$(MINGW)-source
+  artifact: MSYS2-source
   displayName: 'Publish MSYS2 source artifacts'
-
